#!/data/data/com.termux/files/usr/bin/bash

echo "[1/2] TEMEL ANDROID VE KLAVYE İZİNLERİ"
echo "----------------------------------------------------------------"
echo "Lütfen devam etmeden önce şu ayarları yaptığınızdan emin olun:"
echo "1. Ayarlar > Uygulamalar > Termux için 'Diğer uygulamaların"
echo "   üzerinde görüntüle' iznini açın."
echo "2. Termux ve Termux-X11 için pil optimizasyonunu kapatın"
echo "   (Kısıtlanmamış yapın)."
echo "3. Termux-X11 uygulamasını açıp 'Preferences' menüsünden"
echo "   'Prefer scancodes' seçeneğini AÇIK hale getirin."
echo "----------------------------------------------------------------"
read -p "Bu temel ayarları tamamladınız mı? (e/h): " base_confirm

if [[ $base_confirm != "e" && $base_confirm != "E" && $base_confirm != "y" && $base_confirm != "Y" ]]; then
    echo "Lütfen önce ayarları yapın ve betiği tekrar çalıştırın."
    exit 1
fi

echo ""
echo "[2/2] ANDROID PHANTOM PROCESS (ÇÖKME) KISITLAMASI"
echo "----------------------------------------------------------------"
echo "Eğer Linux masaüstünüz aniden siyah ekrana düşüp çöküyorsa, Android'in"
echo "arka plan işlem sınırını (Phantom Process) kaldırmalıyız. Adımları"
echo "hiçbir yeri atlamadan, sırasıyla uygulayın:"
echo ""
echo "1. GELİŞTİRİCİ SEÇENEKLERİNİ AÇIN:"
echo "   - Tabletinizin 'Ayarlar' uygulamasına girin."
echo "   - En alttaki 'Tablet hakkında' menüsüne, ardından 'Yazılım bilgileri'ne girin."
echo "   - Ekranda yazan 'Yapı numarası' yazısına üst üste 7-8 kez hızlıca dokunun."
echo "   - Ekran kilidi şifrenizi sorduğunda girin. Ekranda 'Geliştirici modu "
echo "     açıldı' yazısını göreceksiniz."
echo ""
echo "2. TERMUX'U HAZIRLAYIN:"
echo "   - Termux ekranını açın. Ekranın sol kenarından sağa doğru kaydırarak"
echo "     yan menüyü açın ve 'New session' diyerek yeni bir sekme başlatın."
echo "   - Şu komutu yazıp Enter'a basın: pkg install -y android-tools"
echo ""
echo "3. EKRANI İKİYE BÖLÜN (ÇOK ÖNEMLİ):"
echo "   - Tablette 'Ayarlar' ve 'Termux' uygulamaları ekranı ikiye bölmüş "
echo "     şekilde yan yana açık olmalı. (Uygulamalar arası geçiş yaparsanız "
echo "     güvenlik gereği port numarası anında değişir ve hata alırsınız)."
echo ""
echo "4. KABLOSUZ HATA AYIKLAMA (EŞLEŞTİRME):"
echo "   - Ayarlar'ın en ana menüsüne dönün, en alta inip yeni açılan "
echo "     'Geliştirici seçenekleri' menüsüne girin."
echo "   - Listeden 'Kablosuz hata ayıklama' (Wireless debugging) seçeneğini "
echo "     bulup yanındaki şalteri AÇIK hale getirin."
echo "   - Şalteri açtıktan sonra doğrudan 'Kablosuz hata ayıklama' YAZISINA"
echo "     dokunarak menünün içine girin."
echo "   - 'Cihazı eşleştirme koduyla eşleştir' seçeneğine dokunun."
echo "   - Ekranda kocaman bir 6 haneli kod ve altında 'Bağlantı Noktası' "
echo "     (Port) yazacak. Örn: 192.168.1.5:45678 (Buradaki port 45678'dir)."
echo "   - Termux'a geçip şunu yazın (45678 yerine ekrandaki portu yazın):"
echo "     adb pair 127.0.0.1:45678"
echo "   - Enter'a basın, sizden 'Enter pairing code' isteyecek. Ekrandaki"
echo "     6 haneli eşleştirme kodunu yazıp Enter'a basın. Başarılı diyecektir."
echo ""
echo "5. CİHAZA BAĞLANMA (CONNECT):"
echo "   - Ayarlar kısmındaki eşleştirme penceresini iptal/geri tuşuyla kapatın."
echo "   - Şimdi 'Kablosuz Hata Ayıklama' ANA ekranındasınız. Bu ekranda alt "
echo "     kısımda yer alan 'IP adresi ve Bağlantı noktası' bölümünde YENİ "
echo "     bir port yazar. (Eşleştirme portundan farklıdır)."
echo "   - Termux'a geçip bu yeni portla bağlanın (Örn yeni port 33445 ise):"
echo "     adb connect 127.0.0.1:33445"
echo ""
echo "6. SINIRI KALDIRMA KOMUTU:"
echo "   - Termux'ta 'connected to...' yazısını gördükten sonra son olarak "
echo "     şu uzun komutu yazıp (veya kopyalayıp) Enter'a basın:"
echo "     adb shell device_config put activity_manager max_phantom_processes 2147483647"
echo ""
echo "7. SON AŞAMA:"
echo "   - Komut sessizce çalışır, herhangi bir çıktı vermez. İşlem tamamdır."
echo "   - Yeni ayarların sisteme işlemesi için TABLETİNİZİ YENİDEN BAŞLATIN."
echo "----------------------------------------------------------------"
read -p "Bu ADB işlemini tamamladınız mı? (e/h): " adb_confirm

if [[ $adb_confirm != "e" && $adb_confirm != "E" && $adb_confirm != "y" && $adb_confirm != "Y" ]]; then
    echo "Lütfen önce ADB işlemini yapıp tableti yeniden başlatın."
    exit 1
fi
